// Auto-generated by scripts/generate_assets.py. Do not edit manually.
#ifndef ASSETS_GENERATED_ASSETS_H
#define ASSETS_GENERATED_ASSETS_H

#include "platform/video.h"

extern const video_asset_manifest_t g_video_assets;

#endif /* ASSETS_GENERATED_ASSETS_H */
