#!/usr/bin/env python3
"""
generate_asset_addresses.py

Generate `assets/asset_addresses_output.h` from `assets/asset_addresses.csv`.

Usage:
    python3 scripts/generate_asset_addresses.py \
        --csv assets/asset_addresses.csv \
        --out assets/asset_addresses_output.h

This script will produce #define macros for each Define from the CSV and
EMBED(...) lines for each asset. It overwrites the target file.
"""
import argparse
import csv
import os
import sys


def parse_args():
    parser = argparse.ArgumentParser(description="Generate asset_addresses_output.h from CSV")
    parser.add_argument("--csv", help="Path to assets/asset_addresses.csv", default="assets/asset_addresses.csv")
    parser.add_argument("--out", help="Output header file path", default="assets/asset_addresses_output.h")
    parser.add_argument("--dry-run", action="store_true", help="Print output to stdout instead of writing file")
    return parser.parse_args()


def read_csv(csv_path):
    with open(csv_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = [r for r in reader]
    return rows


def normalize_hex(hex_str):
    if not hex_str:
        return None
    hex_str = hex_str.strip()
    try:
        # Accept values with or without 0x prefix
        value = int(hex_str, 16)
    except ValueError:
        # Maybe the file uses decimal string
        try:
            value = int(hex_str, 10)
        except ValueError:
            raise
    return f"0x{value:X}"


def generate_header(rows):
    # Define lines followed by EMBED lines
    defines = []
    embeds = []
    for r in rows:
        define = (r.get('Define') or '').strip()
        asset = (r.get('Asset') or '').strip()
        path = (r.get('File_Path') or '').strip()
        hex_addr = normalize_hex(r.get('Hex_Address') or '')

        if define and hex_addr:
            defines.append(f"#define {define} {hex_addr}")

        if asset and path and hex_addr:
            # Keep same quoting style as existing source
            embeds.append(f"EMBED({asset}, \"{path}\", {hex_addr});")

    lines = [
        "/* This file is auto-generated by scripts/generate_asset_addresses.py */",
        "/* Do not edit manually. Update assets/asset_addresses.csv instead. */",
        "",
    ]
    lines.extend(defines)
    lines.append("")
    lines.extend(embeds)

    return "\n".join(lines) + "\n"


def main():
    args = parse_args()
    if not os.path.exists(args.csv):
        print(f"CSV file not found: {args.csv}")
        sys.exit(2)

    rows = read_csv(args.csv)
    out_text = generate_header(rows)

    if args.dry_run:
        print(out_text)
        return

    out_dir = os.path.dirname(args.out)
    if out_dir and not os.path.exists(out_dir):
        os.makedirs(out_dir, exist_ok=True)

    with open(args.out, 'w', encoding='utf-8') as f:
        f.write(out_text)

    print(f"Generated {args.out} from {args.csv}")


if __name__ == '__main__':
    main()
