/**
 * @file help_text.h
 * @brief Help text constant for F256 Switcharoo
 */


const char *help_text =
"\n"
"\n"
"            ______ ___  _____   __     _____         _ _       _     \n"
"           |  ____|__ \\| ____| / /    / ____|       (_) |     | |    \n"
"           | |__     ) | |__  / /_   | (_____      ___| |_ ___| |__  \n"
"           |  __|   / /|___ \\| '_ \\   \\___ \\ \\ /\\ / / | __/ __| '_ \\ \n"
"           | |     / /_ ___) | (_) |  ____) \\ V  V /| | || (__| | | |\n"
"           |_|    |____|____/ \\___/  |_____/ \\_/\\_/ |_|\\__\\___|_| |_|\n"
"\n"
"\n"
"    HOW TO PLAY:\n"
"    1. Objective is to create a connected path between the 2nd and 7th rows.\n"
"    2. A piece moves one cell in any direction.\n"
"    3. A piece may exchange positions with an opponent's adjacent piece. Both\n"
"       pieces are marked with a crown to indicate they have been swapped.\n"
"    4. Swapped pieces cannot be the target of a swapping move.\n"
"    5. When a piece is moved to an empty cell, swapped pieces are cleared\n"
"       based on the current selected swapping rule.\n"
"\n"
"    SWAP RULES:\n"
"    Any - All:  Any move to empty cell clears all swapped pieces.\n"
"    Any - Own:  Any move to empty cell clears the player's pieces.\n"
"    Swap - All: Swapped piece move to empty cell clears all.\n"
"    Swap - Own: Swapped piece move to empty cell clears player's pieces.\n"
"\n"
"    PUZZLES:\n"
"    Puzzles are forced Wins in 2, 3 or 4 moves. The objective is \n"
"    to find the winning line in the specified number of moves.\n"
"\n"
"    FREE PLAY:\n"
"    There are 4 starting boards.  Boards with pieces in the center have\n"
"    more immediate tactical play.\n"
"\n"
"    ACTIONS AND HOTKEYS:\n"
"    Select piece with mouse and click a legal target cell to move.\n"
"    You can also use cursor keys and space or enter to select pieces\n"
"    and target cells.\n"
"\n"
"    Mode (M):         Toggle between Puzzle and Free play mode.\n"
"    Reset (R):        Reset the current board back to the starting position.\n"
"    Previous (P):     Previous puzzle or starting board.\n"
"    Next (N):         Next puzzle or starting board.\n"
"    Swap-Rule (S):    Select a swap rule for puzzle or free play.\n"
"    Difficulty (D):   Select an engine difficulty.\n"
"    Hint (H):         Provide a hint for the puzzle or free play position.\n"
"    Achievements (A): View achievements and statistics.\n"
"    Exit (X):         Exit the game.\n"
"\n"
"    TIPS:\n"
"    1. Use swaps to form blockades\n"
"    2. Use adjacent pieces on a row for more than one attack\n"
"    3. Breakup opponent's connection progress by swapping pieces.\n"
"    4. Move to empty cells for better positioning or to break blockades.\n"
"\n"
"\n"
"                            Press [SPACE] to exit.\n";

